apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: aegit7eai-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: aegit7eai-python 
  name: aegit7eai-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: aegit7eai-python 
